spring:
  profiles:
    include: aws
  datasource:
    url: jdbc:h2:tcp://localhost/~/spongedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #registration
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

  # jwt
  jwt:
    secret: ${JWT_SECRET}
    expire-length: 86400000

logging.level:
  org.hibernate.SQL: debug